### PR TITLE
Make sure we can handle arbitrarily aligned objects.

### LINKED ISSUE #22: Should we restrict alignment of objects?
At the moment we require objects to have machine-word alignment, but we don't document this. Currently I'm not sure what the performance consequences of relaxing this are. We should resolve this one way or another.

### PR DESCRIPTION
**Pull request by ltratt**
Previously we could not handle objects which had an alignment greater than a usize. This commit changes the way we store things but does so in a way that doesn't make the expected standard case worse (indeed, the machine code for yksom remains the same before/after this change).

In essence we store a vtable pointer followed (without padding) by an object. The vtable pointer is aligned to a machine word; the object will be aligned to `max(align(usize), align(obj))`. That means that the vtable pointer might not be at the beginning of the memory block.

For a word (or smaller) aligned object on a 64-bit machine the layout will look as follows (in bytes):

```
  0..7: vtable ptr
  8..:  object
```

i.e. the same as we had before. However, for a 32-byte aligned object the layout will be:

```
  0..23:  padding
  24..31: vtable ptr
  32..:   object
```

In this later case the pointer that we store in the struct is an interior pointer (pointing to the beginning of the vtable pointer). Since, in general, we don't expect many people to store objects whose alignment is bigger than a word,
the inevitable slow-down in such a case seems a price worth paying.

The base pointer of the memory block can be recovered using `object`'s alignment (accessible via its vtable) if necessary.

Fixes https://github.com/softdevteam/natrob/issues/22.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
This does now mean that given an arbitrary base pointer to `ThinObj` where we have no type or alignment information, we will be unable to reconstruct it based on a known layout. Do you think this could be a problem?

**Comment by ltratt** [comment]
> This does now mean that given an arbitrary base pointer to ThinObj where we have no type or alignment information, we will be unable to reconstruct it based on a known layout.

Aha, but we do! The `vtable` tells us the object's alignment, from which we can recover how much padding there is before the `vtable` and hence the memory block's overall start and size.

**Comment by jacob-hughes** [comment]
Sorry I should have been more clear. I meant if we have a pointer to the base of the block of memory, we now can't be sure that the vtable resides at the 0'th address. I'm not sure this is even a problem, since I struggle to think of a scenario where this could happen and we don't have type information.

**Comment by ltratt** [comment]
Agreed, I don't think this is an issue, but if it is, we can probably come up with a solution. So long as you've got a pointer to the vtable, you're all good.

**Comment by jacob-hughes** [comment]
Okay, it LGTM.

bors r+

**Pull request merged**
