### PR TITLE
Remove abgc support.

### PR DESCRIPTION
**Pull request by ltratt**
This is no longer maintained.

### CODE REVIEW

**Review by jacob-hughes — APPROVED** [review]
LGTM

**Comment by jacob-hughes** [comment]
Your build failure is the same as the one I had earlier btw. It's because rustfmt is broken on nightly. Unfortunately though this is a travis repo so you can't just use the buildbot script from rboehm.

**Comment by ltratt** [comment]
Thanks. I'm digging into another error elsewhere, so will get back to this.

**Comment by ltratt** [comment]
@jhughes I suggest rebasing this against master as then we can use bors instead of buildbot. OK?

**Comment by jacob-hughes** [comment]
Sure. I think you'll still need to make rustfmt conditional though or buildbot will fail too.

**Comment by ltratt** [comment]
Rebased. Let's see if it works!

**Pull request merged**
