### PR TITLE
Rename gc feature flag

### PR DESCRIPTION
**Pull request by jacob-hughes**

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Agh, sorry I pushed this too quickly and forgot to include part of the commit. One moment...

**Comment by jacob-hughes** [comment]
Ok fixed here (b72fbcff05b158b7fd09e3909c8a86458c8c5a64) and ready for review.

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
