### PR TITLE
Reflect change in rboehm API.

### PR DESCRIPTION
**Pull request by ltratt**
See https://github.com/softdevteam/rboehm/pull/13.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
LGTM

**Comment by ltratt** [comment]
This one can be bors'd independently of https://github.com/softdevteam/rboehm/pull/13 because we don't really have tests for it. Which is naughty, but perhaps for another PR.

**Comment by jacob-hughes** [comment]
Sure. bors r+

**Comment by ltratt** [comment]
I think the `bors` bit might need to be on a newline. Warning: I might be wrong.

**Comment by jacob-hughes** [comment]
Yeah it seems so.

bors r+

**Comment by ltratt** [comment]
Gah, `rustc-ap-rustc_errors` will be the death of me.

```
   Compiling rustc-ap-rustc_errors v664.0.0
error[E0635]: unknown feature `const_transmute`
  --> /home/buildbot-worker1/worker1/buildbot-build-script/build/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_ast-664.0.0/lib.rs:13:12
   |
13 | #![feature(const_transmute)]
   |            ^^^^^^^^^^^^^^^
```

I suggest we try another nightly tomorrow and cross our fingers this problem is solved.

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@jacob-hughes I think this one is ready for merging now.

**Pull request merged**
