### PR TITLE
Move from Travis to Buildbot.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try-

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 I think this is ready for review.

**Review by vext01 — APPROVED** [review]
LGTM

**Comment by vext01** [comment]
bors r+

(Don't forget to kill the green merge button in the repo settings)

**Comment by ltratt** [comment]
> (Don't forget to kill the green merge button in the repo settings)

Already done!

**Pull request merged**
