### PR TITLE
Leave a comment about how we can make recover safer one day in the future

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Review by vext01 — APPROVED** [review]
LGTM

**Comment by vext01** [comment]
```
thread 'main' panicked at 'Multiple candidates for libnatrob.so', proc_macro_tests/run.rs:41:9

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: test failed, to rerun pass '--test proc_macro_tests'

The command "cargo test" exited with 101.
```

**Comment by ltratt** [comment]
Hmm. OK, I might have an idea for that.

**Comment by ltratt** [comment]
OK, so there was a stale cache on Travis, so deleting the cache solves the problem. However, the second Travis check hasn't even run -- @vext01 I think you'd worked out the solution to that problem?

**Comment by vext01** [comment]
> @vext01 I think you'd worked out the solution to that problem?

Is this the thing lukas was experiencing yesterday? I don't know much about it I'm afraid.

**Pull request merged**
