### PR TITLE
Use type punning to expose the instantiated type `T` to the GC.

### PR DESCRIPTION
**Pull request by ltratt**
Previously natrob used Gc::new_from_layout to perform its tricks. However, that meant that we had to use `Gc::<T>::new_from_layout` to tell the GC the "base type". This wasn't safe as we didn't know for sure how/where the GC might lay out its memory (e.g. due to alignment).

This commit changes things so that `natrob::new` now uses type punning to avoid this problem. In essence we add a new struct and a union so that (expanded) natrob looks like:

```
union {
  short: struct T { vtable } // #struct_short_id
  long: struct U { vtable, obj } // #struct_long_id
}
```

The union and the two structs are all `repr(C)` to guarantee layout (C99 guarantees that if a union's constituent structs share the same values then one can safely pun between them). We also rely on Rust's guarantee that
`ManuallyDrop` does not affect layout. We can then safely move between the "short" and "long" representations. The nice thing is that this makes clear to `Gc` what the "base" type is while still keeping us in the land of defined
behaviour.

This assumes that the `Gc<T>` is fine with being type-punned to `Gc<U>` iff `T` and `U` can be safely type punned. We have implicitly made that guarantee and I think we can now be clear about why it's useful!

natrob::new_from_layout still uses the "old" not-strictly-safe layout tricks and I think the next stage will be to get rid of that entirely (which means changing yksom).

### CODE REVIEW

**Comment by ltratt** [comment]
I think I might be able to improve / strengthen this a bit further -- give me a couple of hours.

**Comment by jacob-hughes** [comment]
Ok. I'm pretty happy with this. I can't see any obvious problems with it. This will make it easier to use the trait system for various GC things (`NoTrace`, `NoFinalize` etc). Let me know when you're ready for me to have another look.

**Comment by ltratt** [comment]
https://github.com/softdevteam/natrob/pull/34/commits/d3ab660e63594bd735343dd1dc64ccf887e475b5 pushes this change more deeply through natrob. On the plus side it reduces the complexity and probable-UB quite a bit *but* it does mean that natrob can no longer deal with objects that have a different alignment to `#struct_long_id<u8>` (in practise that probably means "objects that have an alignment greater than a machine word") (the `assert` that enforces this is fixed in https://github.com/softdevteam/natrob/pull/34/commits/2196488ebf6926e30ec30bf8c68c857a1375f5ed due to my being an idiot).

**Comment by jacob-hughes** [comment]
Ok, this LGTM, please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
